name: tictactoe_gameapp
description: "A new Flutter project for playing tic tac toe game." # "A new Flutter project" lastest description
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  agora_rtc_engine: ^6.3.2
  agora_token_service: ^0.1.2
  animated_text_kit: ^4.2.2
  any_link_preview: ^3.0.2
  audio_session: ^0.1.23
  awesome_notifications: null
  bottom_sheet: ^4.0.4
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.15.10
  concentric_transition: ^1.0.3
  confetti: ^0.7.0
  cupertino_icons: ^1.0.6
  curved_navigation_bar: ^1.0.6
  cyber_punk_tool_kit_ui: ^0.1.2
  dotted_border: ^2.1.0
  emoji_picker_flutter: null
  firebase_auth: ^4.18.0
  firebase_core: ^2.27.2
  firebase_storage: ^11.6.11
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_card_swiper: ^7.0.2
  flutter_chat_bubble: ^2.0.2
  flutter_dotenv: ^5.2.1
  flutter_inappwebview: ^6.0.0
  flutter_map: ^7.0.2
  flutter_polls: ^0.1.6
  flutter_settings_ui: ^3.0.1
  flutter_svg: ^2.0.9
  flutter_tts: ^3.8.5
  form_field_validator: ^1.1.0
  geolocator: ^7.7.1
  get: ^4.6.6
  get_storage: ^2.1.1
  giphy_picker: ^3.0.2
  google_generative_ai: ^0.4.5
  google_nav_bar: ^5.0.6
  google_sign_in: ^6.2.1
  image_picker: ^1.0.7
  internet_connection_checker: ^2.0.0
  just_audio: ^0.9.39
  latlong2: ^0.9.1
  lite_rolling_switch: ^1.0.1
  permission_handler: ^11.3.1
  share_plus: ^10.0.0
  speech_to_text: null
  uuid: ^4.4.0
dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/appLogo.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/photos/
    - assets/audios/
    - assets/gifs/
    - assets/champions/
    - assets/effectings/
    - assets/borders/
    - assets/emotes/
    - assets/jajas/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron-Regular.ttf
          weight: 400
        - asset: assets/fonts/Orbitron-Medium.ttf
          weight: 500
        - asset: assets/fonts/Orbitron-SemiBold.ttf
          weight: 600
